import os
import random
import tree_sitter_python as tspython
from tree_sitter import Language, Parser
from datasets import load_dataset
import re
import dotenv

PY_LANGUAGE = Language(tspython.language())
parser = Parser(PY_LANGUAGE)

FIM_PREFIX = "<|pre|>"
FIM_SUFFIX = "<|suf|>"
FIM_MIDDLE = "<|mid|>"
CURSOR = "<|cur|>"
DIFF = "<|diff|>"

MAX_SUFFIX_CHARS = 1000
MAX_DIFF_BLOCKS = 5
MIN_DIFF_BLOCKS = 1

class PythonDiffDataset:
    def __init__(self):
        dotenv.load_dotenv()
        hf_token = os.environ.get("HF_TOKEN", "uhhh no token for you")
        if not hf_token:
            print("Warning: No HF_TOKEN found.")
        self.dataset = load_dataset(
            "bigcode/the-stack-dedup",
            data_dir="data/python",
            split="train",
            streaming=True,
            token=hf_token
        )

    def is_valid(self, content):
        lines = content.split("\n")
        num_lines = len(lines)
        
        if num_lines > 8000 or num_lines < 40:
            return False
        
        max_line_length = max(len(line) for line in lines)
        if max_line_length > 1000:
            return False
        
        avg_line_length = len(content) / max(1, num_lines)
        if avg_line_length > 100:
            return False
        
        alnum_count = sum(c.isalnum() for c in content)
        if (alnum_count / len(content)) < 0.25:
            return False
        
        eq_count = content.count('=')
        if (eq_count / num_lines) < 0.05:
            return False
        
        autogenerated_patterns = [
            r"<autogenerated\s*/>",
            r"generated by",
            r"auto-generated",
            r"do not edit",
            r"machine generated",
        ]
        content_lower = content.lower()
        for pattern in autogenerated_patterns:
            if re.search(pattern, content_lower):
                return False
        
        return True

    def generate_diff_block(self, lines, line_idx):
        old_line = lines[line_idx]
        
        if not old_line.strip():
            return None, lines
        
        block_types = [("replace", 0.6), ("insert", 0.25), ("delete", 0.15)]
        block_type = random.choices(
            [t[0] for t in block_types],
            weights=[t[1] for t in block_types],
            k=1
        )[0]
        
        if block_type == "replace":
            new_line = self._mutate_line(old_line)
            if new_line == old_line:
                return None, lines
            block = f"- {old_line}\n+ {new_line}"
            new_lines = lines[:line_idx] + [new_line] + lines[line_idx + 1:]
            return block, new_lines
        
        elif block_type == "insert":
            new_line = self._generate_insert_line(lines, line_idx)
            block = f"+ {new_line}"
            new_lines = lines[:line_idx] + [new_line] + lines[line_idx:]
            return block, new_lines
        
        elif block_type == "delete":
            block = f"- {old_line}"
            new_lines = lines[:line_idx] + lines[line_idx + 1:]
            return block, new_lines
        
        return None, lines

    def _mutate_line(self, line):
        if not line.strip():
            return line
        
        mutations = [
            self._rename_identifier,
            self._change_string_content,
            self._change_number,
            self._change_operator,
            self._swap_boolean,
        ]
        
        random.shuffle(mutations)
        for mutation in mutations:
            result = mutation(line)
            if result != line:
                return result
        return line

    def _rename_identifier(self, line):
        match = re.search(r'(?<![.\'\"])(?<!__)([a-z][a-z0-9_]*)\s*=(?!=)', line)
        if match:
            old_name = match.group(1)
            if old_name.startswith('__') or old_name in ('self', 'cls', 'if', 'for', 'while', 'def', 'class', 'return', 'import', 'from', 'in', 'is', 'not', 'and', 'or'):
                return line
            prefixes = ["new_", "updated_", "tmp_", "local_"]
            new_name = random.choice(prefixes) + old_name
            return line.replace(old_name + " =", new_name + " =", 1)
        
        match = re.search(r'def\s+([a-z][a-z0-9_]*)\s*\(', line)
        if match:
            old_name = match.group(1)
            if old_name.startswith('__') or old_name.endswith('__'):
                return line
            suffixes = ["_v2", "_updated", "_new", "_alt"]
            new_name = old_name + random.choice(suffixes)
            return line.replace(f"def {old_name}(", f"def {new_name}(", 1)
        
        return line

    def _change_string_content(self, line):
        match = re.search(r'(["\'])([^"\']+)\1', line)
        if match:
            quote = match.group(1)
            content = match.group(2)
            modifications = [
                content.upper() if content.islower() else content.lower(),
                content + "_v2",
                "updated_" + content,
                content.replace("_", "-") if "_" in content else content.replace("-", "_"),
            ]
            new_content = random.choice([m for m in modifications if m != content] or [content + "_mod"])
            return line.replace(f'{quote}{content}{quote}', f'{quote}{new_content}{quote}', 1)
        return line

    def _change_number(self, line):
        match = re.search(r'(?<![a-zA-Z_])(\d+)(?![a-zA-Z_])', line)
        if match:
            num = int(match.group(1))
            new_num = num + random.choice([1, 5, 10, -1, 2])
            if new_num < 0:
                new_num = num + 1
            start, end = match.span(1)
            return line[:start] + str(new_num) + line[end:]
        return line

    def _change_operator(self, line):
        if '__name__' in line or '__main__' in line:
            return line
        ops = [('==', '!='), ('!=', '=='), ('<=', '>='), ('>=', '<='), 
               (' < ', ' > '), (' > ', ' < '), (' + ', ' - '), (' - ', ' + '),
               (' and ', ' or '), (' or ', ' and ')]
        for old_op, new_op in ops:
            if old_op in line:
                return line.replace(old_op, new_op, 1)
        return line

    def _swap_boolean(self, line):
        if 'True' in line:
            return line.replace('True', 'False', 1)
        if 'False' in line:
            return line.replace('False', 'True', 1)
        if 'None' in line and '=' in line:
            return line.replace('None', '[]', 1)
        return line

    def _generate_insert_line(self, lines, line_idx):
        if line_idx > 0:
            prev_line = lines[line_idx - 1]
            indent = len(prev_line) - len(prev_line.lstrip())
        else:
            indent = 0
        
        templates = [
            "pass",
            "# TODO: implement",
            "result = None",
            "continue",
            "break",
        ]
        
        return " " * indent + random.choice(templates)

    def generate_edit_sequence(self, content):
        lines = content.split("\n")
        num_blocks = random.randint(MIN_DIFF_BLOCKS, MAX_DIFF_BLOCKS)
        
        blocks = []
        current_lines = lines[:]
        
        for _ in range(num_blocks):
            if len(current_lines) < 5:
                break
            
            line_idx = random.randint(2, len(current_lines) - 3)
            block, current_lines = self.generate_diff_block(current_lines, line_idx)
            if block:
                blocks.append(block)
        
        return blocks, current_lines

    def generate_diff_example(self, content):
        lines = content.split("\n")
        
        cursor_line = random.randint(len(lines) // 4, 3 * len(lines) // 4)
        
        prefix_lines = lines[:cursor_line]
        suffix_lines = lines[cursor_line:]
        
        prefix_text = "\n".join(prefix_lines)
        suffix_text = "\n".join(suffix_lines)
        
        if len(suffix_text) > MAX_SUFFIX_CHARS:
            suffix_text = suffix_text[:MAX_SUFFIX_CHARS]
        
        blocks, _ = self.generate_edit_sequence(content)
        
        if len(blocks) < 2:
            blocks, _ = self.generate_edit_sequence(content)
        
        if len(blocks) < 1:
            return None
        
        history_blocks = blocks[:-1]
        target_block = blocks[-1]
        
        prompt = FIM_SUFFIX + "\n" + suffix_text + "\n"
        prompt += FIM_PREFIX + "\n" + prefix_text + "\n"
        
        for block in history_blocks:
            prompt += DIFF + "\n" + block + "\n"
        
        prompt += DIFF + "\n"
        
        target = target_block + "\n" + DIFF
        
        return {
            "prompt": prompt,
            "target": target,
            "num_history_blocks": len(history_blocks),
            "prefix": prefix_text,
            "suffix": suffix_text,
        }

    def __iter__(self):
        for item in self.dataset:
            content = item["content"]
            if not self.is_valid(content):
                continue
            
            content_lines = content.split('\n')
            content_lines = [line for line in content_lines if line.strip() != ""]
            clean_content = "\n".join(content_lines)
            
            example = self.generate_diff_example(clean_content)
            if example:
                yield example
